export const shooterGames = [
    {
        id: 540,
        title: "Overwatch 2",
        thumbnail: "https://www.freetogame.com/g/540/thumbnail.jpg",
        short_description: "A hero-focused first-person team shooter from Blizzard Entertainment.",
        game_url: "https://www.freetogame.com/open/overwatch-2",
        genre: "Shooter",
        platform: "PC (Windows)",
        publisher: "Activision Blizzard",
        developer: "Blizzard Entertainment",
        release_date: "2022-10-04",
        freetogame_profile_url: "https://www.freetogame.com/overwatch-2",
    },
    {
        id: 516,
        title: "PUBG: BATTLEGROUNDS",
        thumbnail: "https://www.freetogame.com/g/516/thumbnail.jpg",
        short_description: "Get into the action in one of the longest running battle royale games PUBG Battlegrounds.",
        game_url: "https://www.freetogame.com/open/pubg",
        genre: "Shooter",
        platform: "PC (Windows)",
        publisher: "KRAFTON, Inc.",
        developer: "KRAFTON, Inc.",
        release_date: "2022-01-12",
        freetogame_profile_url: "https://www.freetogame.com/pubg",
    },
    {
        id: 508,
        title: "Enlisted",
        thumbnail: "https://www.freetogame.com/g/508/thumbnail.jpg",
        short_description: "Get ready to command your own World War II military squad in Gaijin and Darkflow Software’s MMO squad-based shooter Enlisted. ",
        game_url: "https://www.freetogame.com/open/enlisted",
        genre: "Shooter",
        platform: "PC (Windows)",
        publisher: "Gaijin Entertainment",
        developer: "Darkflow Software",
        release_date: "2021-04-08",
        freetogame_profile_url: "https://www.freetogame.com/enlisted",
    }
]

export const mmorpgGames = [
    {
        id: 582,
        title: "Tarisland",
        developer: "Level Infinite",
        thumbnail: "https://www.freetogame.com/g/582/thumbnail.jpg",
        short_description: "A cross-platform MMORPG developed by Level Infinite and Published by Tencent.",
        game_url: "https://www.freetogame.com/open/tarisland",
        genre: "MMORPG",
        platform: "PC (Windows)",
        publisher: "Tencent",
        release_date: "2024-06-22",
        freetogame_profile_url: "https://www.freetogame.com/tarisland",
    },
    {
        id: 590,
        title: "Throne And Liberty",
        developer: "NCSoft",
        thumbnail: "https://www.freetogame.com/g/590/thumbnail.jpg",
        freetogame_profile_url: "https://www.freetogame.com/throne-and-liberty",
        game_url: "https://www.freetogame.com/open/throne-and-liberty",
        genre: "MMORPG",
        platform: "PC (Windows)",
        publisher: "Amazon Games",
        release_date: "2024-10-01",
        short_description: "A free-to-play multi-platorm MMORPG from NCSoft and Amazon Games.",


    },
    {
        id: 11,
        title: "Neverwinter",
        developer: "Cryptic Studios",
        thumbnail: "https://www.freetogame.com/g/11/thumbnail.jpg",
        freetogame_profile_url: "https://www.freetogame.com/neverwinter",        
        game_url: "https://www.freetogame.com/open/neverwinter",
        genre: "MMORPG",
        platform: "PC (Windows)",
        publisher: "Perfect World Entertainment",
        release_date: "2013-12-06",
        short_description: "A free-to-play 3D action MMORPG based on the acclaimed Dungeons & Dragons fantasy roleplaying game. ",
    }
]

export const cardGames = [
    {
        developer: "Comico Games",
        freetogame_profile_url: "https://www.freetogame.com/screenplay",
        game_url: "https://www.freetogame.com/open/screenplay",
        genre: "Card Game",
        id: 580,
        platform: "PC (Windows)",
        publisher: "Comico Games",
        release_date: "2024-05-13",
        short_description: "A collectible card game inspired by movie making.",
        thumbnail: "https://www.freetogame.com/g/580/thumbnail.jpg",
        title: "Screenplay CCG",
    },
    {
        developer: "Richard Garfield, Justin Gary",
        freetogame_profile_url: "https://www.freetogame.com/solforge-fusion",
        game_url: "https://www.freetogame.com/open/solforge-fusion",
        genre: "Card Game",
        id: 585,
        platform: "PC (Windows)",
        publisher: "Stone Blade Entertainment",
        release_date: "2024-04-16",
        short_description: "A card-battling game in which each card levels up and becomes more powerful.",
        thumbnail: "https://www.freetogame.com/g/585/thumbnail.jpg",
        title: "SolForge Fusion",
    }, {
        developer: "Fobia",
        freetogame_profile_url: "https://www.freetogame.com/destinys-divide",
        game_url: "https://www.freetogame.com/open/destinys-divide",
        genre: "Card Game",
        id: 569,
        platform: "PC (Windows)",
        publisher: "Fobia",
        release_date: "2023-11-03",
        short_description: "Free-to-play PvP Fantasy Card Game for competitive card game players.",
        thumbnail: "https://www.freetogame.com/g/569/thumbnail.jpg",
        title: "Destiny's Divide",
    }
]